name: Github Pages - Production

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Angular to GitHub Pages
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          install_command: "yarn"
          build_command: "npm run build"
    # - name: 'Build'
    #   shell: bash
    #   run: |
    #     echo "::group::Build"
    #     ${{ inputs.install_command }}
    #     ${{ inputs.build_command }}
    #     echo "::endgroup::"
    # - name: 'upload'
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: ${{ inputs.path }}

    # - id: deploy
    #   name: Deploy to GitHub Pages
    #   uses: actions/deploy-pages@v4
    #   with:
    #     token: ${{ github.token }}
